/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/3DModels/car.glb 

This is the 3D model of the car, I imported it from an asset store on blender and brought it here using gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const CarModel = (props) => {
  const { nodes, materials } = useGLTF('/3DModels/car.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['DMC_Sci-Fi_Hover_Car'].geometry} material={materials['Hover DMC']} position={[-0.235, 0, 0.412]} scale={2.357} />
    </group>
  )
}
export default CarModel;
useGLTF.preload('/3DModels/car.glb')
