/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/3DModels/donut.glb 
This is the 3D model of the donut, I imported it from an asset store on blender and brought it here using gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

const Donut = (props) => {
  const { nodes, materials } = useGLTF('/3DModels/donut.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.icing.geometry} material={materials['chocolate.002']} position={[-0.019, 0.006, -0.125]} rotation={[-Math.PI, 0.536, -Math.PI]} scale={34.689} />
      <mesh geometry={nodes.donut.geometry} material={materials['donut.001']} position={[-0.019, 0.006, -0.125]} rotation={[-Math.PI, 0.536, -Math.PI]} scale={34.689} />
    </group>
  )
}
export default Donut;
useGLTF.preload('/3DModels/donut.glb')
